version: '3.8'


services:
   web:
       build:
         dockerfile: ../docker/Dockerfile
         context: ../project

       volumes:
        - ../project:/srv/www/project
       expose:
         - 8080
       ports:
           - 8080:8080
       command: "gunicorn -c gunicorn.py designpro.wsgi"

