version: '3.8'


services:
   web:
       build:
         dockerfile: ../Dockerfile
         context: ../project
       command: python3.10 manage.py runserver 0.0.0.0:8080
       volumes:
        - ../project:/srv/www/project
       expose:
         - 8080
       ports:
           - 8080:8080
       #command: "gunicorn -c gunicorn.py designpro.wsgi"

